<a href="https://colab.research.google.com/github/junxnone/examples/blob/master/tensorflow/add_concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf

TensorFlow 2.x selected.


In [0]:
t1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
t2 = [[7, 8, 9], [10, 11, 12], [0, 1, 2]]

In [3]:
tf.concat([t1, t2], 0)

<tf.Tensor: id=3, shape=(6, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  1,  2]], dtype=int32)>

In [4]:
tf.concat([t1, t2], 1)

<tf.Tensor: id=7, shape=(3, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12],
       [ 7,  8,  9,  0,  1,  2]], dtype=int32)>

In [5]:
tf.shape(t1) 

<tf.Tensor: id=9, shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [6]:
tf.shape(tf.concat([t1, t2], 0)) 

<tf.Tensor: id=14, shape=(2,), dtype=int32, numpy=array([6, 3], dtype=int32)>

In [7]:
tf.shape(t2) 

<tf.Tensor: id=16, shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [8]:
tf.shape(tf.concat([t1, t2], 1)) 

<tf.Tensor: id=21, shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [0]:
t3 = [t1, t2, t1]
t4 = [t2, t1, t2]

In [10]:
tf.shape(t3)

<tf.Tensor: id=23, shape=(3,), dtype=int32, numpy=array([3, 3, 3], dtype=int32)>

In [11]:
tf.concat([t3,t4], 0)

<tf.Tensor: id=27, shape=(6, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  1,  2]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  1,  2]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  1,  2]]], dtype=int32)>

In [12]:
tf.shape(tf.concat([t3, t4], 0))

<tf.Tensor: id=32, shape=(3,), dtype=int32, numpy=array([6, 3, 3], dtype=int32)>

> 6 类似图像中的通道，DL 中解释为 t3 和 t4 3 channel feature map Concat 后形成了 6 channel 的feature map