<a href="https://colab.research.google.com/github/junxnone/examples/blob/master/tensorflow/tf_extract_image_patches.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- [tf.extract_image_patches()](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches)

```
tf.image.extract_patches(
    images,
    sizes,
    strides,
    rates,
    padding,
    name=None
)
```
- images: 4 维 Tensor. Shape = `[batch, in_rows, in_cols, depth]
- sizes: 获取 patch 的大小. Shape = [1, size_rows, size_cols, 1].
- strides: 1 维 Tensor. Shape = [1, stride_rows, stride_cols, 1]. 两个patch 中心距离.
- rates: 1 维 Tensor. Shape = [1, rate_rows, rate_cols, 1]. 隔多少点取一个 pixel，类似 dilate 卷积.
- padding: `VALID` patch 必须在图像内，`SAME` patch 部分可以不在图像内，超出部分填充 `0`.
- name: A name for the operation (optional).

In [1]:
import tensorflow as tf

In [2]:
n = 10
images = [[[[x * n + y + 1] for y in range(n)] for x in range(n)]]
for i in range(0,10):
  print(images[0][i])

[[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]
[[11], [12], [13], [14], [15], [16], [17], [18], [19], [20]]
[[21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
[[31], [32], [33], [34], [35], [36], [37], [38], [39], [40]]
[[41], [42], [43], [44], [45], [46], [47], [48], [49], [50]]
[[51], [52], [53], [54], [55], [56], [57], [58], [59], [60]]
[[61], [62], [63], [64], [65], [66], [67], [68], [69], [70]]
[[71], [72], [73], [74], [75], [76], [77], [78], [79], [80]]
[[81], [82], [83], [84], [85], [86], [87], [88], [89], [90]]
[[91], [92], [93], [94], [95], [96], [97], [98], [99], [100]]


In [3]:
with tf.Session() as sess:
    print('\nstrides 取 5:')
    print(tf.extract_image_patches(images=images, ksizes=[1, 3, 3, 1], strides=[1, 5, 5, 1], rates=[1, 1, 1, 1], padding='VALID').eval())


strides 取 5:
Instructions for updating:
ksizes is deprecated, use sizes instead
[[[[ 1  2  3 11 12 13 21 22 23]
   [ 6  7  8 16 17 18 26 27 28]]

  [[51 52 53 61 62 63 71 72 73]
   [56 57 58 66 67 68 76 77 78]]]]


```
 *  *  *  4  5  *  *  *  9 10
 *  *  * 14 15  *  *  * 19 20
 *  *  * 24 25  *  *  * 29 30
31 32 33 34 35 36 37 38 39 40
41 42 43 44 45 46 47 48 49 50
 *  *  * 54 55  *  *  * 59 60
 *  *  * 64 65  *  *  * 69 70
 *  *  * 74 75  *  *  * 79 80
81 82 83 84 85 86 87 88 89 90
91 92 93 94 95 96 97 98 99 100
```

In [4]:
with tf.Session() as sess:
    print('\nrates 取 2:')
    print(tf.extract_image_patches(images=images, ksizes=[1, 3, 3, 1], strides=[1, 5, 5, 1], rates=[1, 2, 2, 1], padding='VALID').eval())


rates 取 2:
[[[[  1   3   5  21  23  25  41  43  45]
   [  6   8  10  26  28  30  46  48  50]]

  [[ 51  53  55  71  73  75  91  93  95]
   [ 56  58  60  76  78  80  96  98 100]]]]


```
   *  2  *  4  *  x  7  x  9  x
  11 12 13 14 15 16 17 18 19 20
   * 22  * 24  *  x 27  x 29  x
  31 32 33 34 35 36 37 38 39 40
   * 42  * 44  *  x 47  x 49  x
   + 52  + 54  +  o 57  o 59  o
  61 62 63 64 65 66 67 68 69 70
   + 72  + 74  +  o 77  o 79  o
  81 82 83 84 85 86 87 88 89 90
   + 92  + 94  +  o 97  o 99  o
```

In [5]:
with tf.Session() as sess:
    print('\nstrides 取 7, 图像不足以取第二个patch:')
    print(tf.extract_image_patches(images=images, ksizes=[1, 4, 4, 1], strides=[1, 7, 7, 1], rates=[1, 1, 1, 1], padding='VALID').eval()) 


strides 取 7, 图像不足以取第二个patch:
[[[[ 1  2  3  4 11 12 13 14 21 22 23 24 31 32 33 34]]]]


```
 *  *  *  *  5  6  7  8  9 10
 *  *  *  * 15 16 17 18 19 20
 *  *  *  * 25 26 27 28 29 30
 *  *  *  * 35 36 37 38 39 40
41 42 43 44 45 46 47 48 49 50
51 52 53 54 55 56 57 58 59 60
61 62 63 64 65 66 67 68 69 70
71 72 73 74 75 76 77 78 79 80
81 82 83 84 85 86 87 88 89 90
91 92 93 94 95 96 97 98 99 100
```

In [6]:
with tf.Session() as sess:
    print('\npadding 取 SAME, 不足部分填充 0:')
    print(tf.extract_image_patches(images=images, ksizes=[1, 4, 4, 1], strides=[1, 7, 7, 1], rates=[1, 1, 1, 1], padding='SAME').eval())


padding 取 SAME, 不足部分填充 0:
[[[[  1   2   3   4  11  12  13  14  21  22  23  24  31  32  33  34]
   [  8   9  10   0  18  19  20   0  28  29  30   0  38  39  40   0]]

  [[ 71  72  73  74  81  82  83  84  91  92  93  94   0   0   0   0]
   [ 78  79  80   0  88  89  90   0  98  99 100   0   0   0   0   0]]]]


```
 *  *  *  *  5  6  7  *  *  * +0
 *  *  *  * 15 16 17  *  *  * +0
 *  *  *  * 25 26 27  *  *  * +0
 *  *  *  * 35 36 37  *  *  * +0
41 42 43 44 45 46 47 48 49 50
51 52 53 54 55 56 57 58 59 60
61 62 63 64 65 66 67 68 69 70
 *  *  *  * 75 76 77  *  *  * +0
 *  *  *  * 85 86 87  *  *  * +0
 *  *  *  * 95 96 97  *  *  * +0
+0 +0 +0 +0          +0 +0 +0 +0
```