In [21]:
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.metrics.pairwise import pairwise_kernels
from sklearn.metrics.pairwise import manhattan_distances
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics.pairwise import paired_euclidean_distances

In [2]:
X = np.array([[2, 3], [3, 5], [5, 8]])
Y = np.array([[1, 0], [2, 1]])

# 计算euclidean 距离

In [16]:
euclidean_distances(X,Y)

array([[3.16227766, 2.        ],
       [5.38516481, 4.12310563],
       [8.94427191, 7.61577311]])

## 成对计算euclidean 距离

In [29]:
paired_euclidean_distances(Y, Y+1)

array([1.41421356, 1.41421356])

# 计算 cosine 距离

In [17]:
pairwise_distances(X, Y, metric='cosine')

array([[0.4452998 , 0.13175686],
       [0.48550424, 0.15633851],
       [0.47000106, 0.14671817]])

In [20]:
cosine_distances(X, Y)

array([[0.4452998 , 0.13175686],
       [0.48550424, 0.15633851],
       [0.47000106, 0.14671817]])

# 计算X，Y的manhattan 距离

In [10]:
pairwise_distances(X, Y, metric='manhattan')

array([[ 4.,  2.],
       [ 7.,  5.],
       [12., 10.]])

In [13]:
manhattan_distances(X, Y)

array([[ 4.,  2.],
       [ 7.,  5.],
       [12., 10.]])

# 计算 X,X的manhattan 距离

In [5]:
pairwise_distances(X, metric='manhattan')

array([[0., 3., 8.],
       [3., 0., 5.],
       [8., 5., 0.]])

In [14]:
manhattan_distances(X)

array([[0., 3., 8.],
       [3., 0., 5.],
       [8., 5., 0.]])

# 计算 X，Y的linear 距离

In [8]:
pairwise_kernels(X, Y, metric='linear')

array([[ 2.,  7.],
       [ 3., 11.],
       [ 5., 18.]])