<a href="https://colab.research.google.com/github/junxnone/examples/blob/master/python/random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# random package
- [random](https://docs.python.org/3/library/random.html)
- [numpy.random](https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html)
- [secrets](https://docs.python.org/3/library/secrets.html#module-secrets)

In [0]:
import numpy as np
import secrets
import random

# 1 random
> random package 中指定如果用于安全的部分需要使用 secrts package

- choice : 在sequence 中随机选择
- choices： 在指定 weights的sequence 中随机选择
- shuffle: 打乱sequence，直接改变sequence
- sample：在sequence 随机选择k个
- random ：  [0.0, 1.0)
- uniform(a,b) : a<= N <=b
- randrange(start,stop[,step]): 从start到stop的范围，指定step 中选择
- seed() : 指定随机种子：提供可重复性
- Real-valued distributions
  - gauss
  - betavariate
  - expovariate
  - gammavariate
  - lognormvariate
  - normalvariate
  - vonmisesvariate
  - paretovariate
  - weibullvariate

In [2]:
random.seed(10)
print(random.random())
print(random.uniform(2.5,10.0))
print(random.randrange(10))
print(random.randrange(0, 101, 2))
print(random.choice(['win', 'lose', 'draw']))
dest = 'ace two three four'.split()
random.shuffle(dest) # return None
print(dest) 
print(random.sample(dest,2))
print(random.choices(['red', 'black', 'green'], [18, 18, 2], k=6))

0.5714025946899135
5.716667910063359
9
0
win
['ace', 'three', 'two', 'four']
['three', 'ace']
['black', 'red', 'red', 'green', 'green', 'red']


# 2 numpy.random
- rand
- randn
- randint ： [start,end]
- random_integers : [start,end)
- random_sample
- random
- ranf
- sample
- choice : 第一个参数是int或array，最后一个参数类似weights
- bytes
- shuffle : 多维时，只shuffle 第一维
- permutation
- distributions
  - beta
  - gamma
  - laplace
  - logistic
  - normal
  - ...

In [3]:
print(np.random.random())
print(np.random.rand())
print(np.random.randint(1, 100))
print(np.random.random_integers(1, 100)) # 不推荐使用

0.9535307388150521
0.5546663848830805
67
26


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  after removing the cwd from sys.path.


## shuffle vs permutation

In [4]:
arr = np.arange(10)
arrp = np.random.permutation(arr)
print(arr)
print(arrp)
np.random.shuffle(arr)
print(arr)


arr3 = np.arange(9).reshape((3, 3))
arr3p = np.random.permutation(arr3)
print(arr3)
print(arr3p)
np.random.shuffle(arr3)
print(arr3)



[0 1 2 3 4 5 6 7 8 9]
[0 2 3 1 9 8 7 4 6 5]
[9 3 1 2 4 8 0 7 5 6]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]
 [0 1 2]]


# secrets
> secure random 


- secrets.SystemRandom()
- secrets.choice() : 随机选择非空sequence
- secrets.randbelow(n) ： [0,n)
- secrets.randbits(k) : 随机返回k bits int
- secrets.token_bytes()
- secrets.token_hex()
- secrets.token_urlsafe()
- secrets.compare_digest()





In [5]:
  print(secrets.randbelow(100)/100.0)
  print(secrets.randbits(10))
  print(secrets.token_bytes(5))
  print(secrets.token_hex(5))
  print(secrets.token_urlsafe(5))

0.6
871
b'\xd0L\x7f\xe2\xdf'
4ceba71e99
bcsRz2o


In [6]:
cnt = 0
for i in range(0,100000):
  if secrets.randbelow(100)/100.0 < 0.5:
    cnt+=1
print(cnt)

49815
